### ISSUE TITLE
[Request] Ability to attach multiple CCA components to the same module

### ISSUE THREAD

**Issue by SilverAndro** [sisby-folk/switchy#20]
Currently, if you attempt to call `CardinalSerializerCompat.tryRegister` with the same module name multiple times, all attempts past the first log a warning instead of doing anything. This prevents me from bundling all the CCA components I have into a single module easily, as they are separated due to scope concerns, but don't make sense to actually separate in usage.

**Comment by sisby-folk** [comment]
Hmm, you know when I was writing the RPGStats PR this did occur to me - it would be better if both disabled and enabled at once. I'll have a think about what it might look like to do something like this - I still want to avoid the case where multiple mods can declare a module for the same CCA component.

Writing the generic CCA module so that it worked on a list of components instead of a single one would be a cinch, but it's that identification and duplication part that's a little bit of a concern - I'd like to guard against it.

**Comment by sisby-folk** [comment]
Now that we have the `MODULE_INFO` registry, we may be able to add some kind of list of identifiers to it that prevent other modules from being registered that share them - that way CCA switchy modules could actually be called `namespace:json_file_name`, and include every component in that file.

**Comment by sisby-folk** [comment]
Committed this to the repo now, but there's a generics compile error I don't understand in it right now.

new format looks like

```
{
    "default": true,
    "importable": "ALLOWED",
    "ifModsLoaded": ["lanyard"]
    "components": ["lanyard:profiles"]
}
```

**Comment by sisby-folk** [comment]
Thanks for the help with this one! Closing out with 1.8.1.
