### ISSUE TITLE
Crash with Infinitory Renewed 1.5.0-pre4

### ISSUE THREAD

**Issue by Afrocntrik** [sisby-folk/switchy#53]
Fabric Loader 0.14.22
Minecraft 1.20.1

[crashlog](https://gist.github.com/Afrocntrik/40648c270a99b26d6af0430568babc73)

[Infinitory Renewed](https://modrinth.com/mod/infinitory-renewed) is not open source and is most likely abandoned.

**Comment by sisby-folk** [comment]
To nail this down exactly: infinitory has mixed in to the initializer for PlayerInventory. Switchy inventories constructs player inventories where `player` is `null` in order to store inventory contents for non-current presets. Infinitory runs player.getWorld(), which naturally crashes. Even if it checked for a null player, I'm unsure it would serialize and deserialize its own correctly - assuming it is actually world dependent.

Just choose between switchable inventories and infinite inventories.
