### ISSUE TITLE
1.20.2 support

### ISSUE THREAD

**Issue by DBTDerpbox** [sisby-folk/switchy#64]
Are there any plans to add support for Minecraft 1.20.2?

**Comment by sisby-folk** [comment]
Yep! for the new "experimental hotfix" updates mojang are putting out, our strategy will be always to update _through_ these versions, pushing at least one functional version of the mod out each (even if it might not be maintained). This will happen before 1.21, likely within a couple of months.

**Comment by PsychoBreadstick** [comment]
Hey, are there still any plans for a port specifically to this version of Minecraft? I know it's probably a lot to ask, especially since 1.20.1 and 1.21+ are far more popular versions of Minecraft. However, the main reason I'm asking is because the latest stable version of origins is on 1.20.2, and I and a few others are working on a server for that version, yet there is no version of Switchy available for 1.20.2.

**Comment by sisby-folk** [comment]
the versioning scheme for our mods has changed in the past year such that I'd say that the 1.20.4 version is more of an anomaly - we're sticking to modpack hotfixes for all of our mods, which are consistently signalled as the last hotfix before experimental toggles are added. See #86

for your case, I'd highly recommend 1.20.1 or 1.21.1
